api_platform:
    title: 'Flex'
    description: 'Project description'
    version: '0.0.1'

    mapping:
        paths: [
            '%kernel.project_dir%/src/Module/Gym/Entity',
            '%kernel.project_dir%/src/Module/GymSubscription/Entity',
            '%kernel.project_dir%/src/Module/GymSubscriptionPurchase/Entity',
            '%kernel.project_dir%/src/Module/Media/Entity',
            '%kernel.project_dir%/src/Module/Trainer/Entity',
            '%kernel.project_dir%/src/Module/TrainerSubscription/Entity',
            '%kernel.project_dir%/src/Module/TrainerSubscriptionPurchase/Entity',
            '%kernel.project_dir%/src/Module/User/Entity',
        ]

    patch_formats:
        json: ['application/merge-patch+json']

    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
