doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
#            App:
#                is_bundle: false
#                dir: '%kernel.project_dir%/src/Entity'
#                prefix: 'App\Entity'
#                alias: App
            Gym:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Module/Gym/Entity'
                prefix: 'App\Module\Gym\Entity'
                alias: Gym

            GymSubscription:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Module/GymSubscription/Entity'
                prefix: 'App\Module\GymSubscription\Entity'
                alias: GymSubscription

            GymSubscriptionPurchase:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Module/GymSubscriptionPurchase/Entity'
                prefix: 'App\Module\GymSubscriptionPurchase\Entity'
                alias: GymSubscriptionPurchase

            User:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Module/User/Entity'
                prefix: 'App\Module\User\Entity'
                alias: User

            Media:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Module/Media/Entity'
                prefix: 'App\Module\Media\Entity'
                alias: Media

            Trainer:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Module/Trainer/Entity'
                prefix: 'App\Module\Trainer\Entity'
                alias: Trainer

            TrainerSubscription:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Module/TrainerSubscription/Entity'
                prefix: 'App\Module\TrainerSubscription\Entity'
                alias: TrainerSubscription

            TrainerSubscriptionPurchase:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Module/TrainerSubscriptionPurchase/Entity'
                prefix: 'App\Module\TrainerSubscriptionPurchase\Entity'
                alias: TrainerSubscriptionPurchase

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
